SET IGNORECASE TRUE;

CREATE TABLE contacts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    first_name VARCHAR(100),
    middle_name VARCHAR(100),
    last_name VARCHAR(100),
    pf_number VARCHAR(100),
    id_number VARCHAR(100),
    email_address VARCHAR(100)
);

